services:
  cube:
    image: cubejs/cube:dev
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - DEBUG_LOG=true
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=duckdb
      - CUBEJS_DB_DUCKDB_DATABASE_PATH=securitydb.duckdb
      - CUBEJS_DB_DUCKDB_S3_ACCESS_KEY_ID=test
      - CUBEJS_DB_DUCKDB_S3_ENDPOINT=host.docker.internal:4566
      - CUBEJS_DB_DUCKDB_S3_URL_STYLE=path
      - CUBEJS_DB_DUCKDB_S3_REGION=us-east-1
      - CUBEJS_DB_DUCKDB_S3_SECRET_ACCESS_KEY=test
      - CUBEJS_DB_DUCKDB_S3_USE_SSL=false
    volumes:
      - .:/cube/conf
  # only used for generating the schema
  postgres:
    image: "postgres:14"
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      # - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      # - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      # - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN- }
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  data: